---
- name: install tomcat server
  hosts: worker
  become: yes

  tasks:
  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat-9
      state: directory
      mode: 0755
  - name: download & unarchive
    unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.38/bin/apache-tomcat-9.0.38.tar.gz
      dest: /opt/tomcat-9
      remote_src: yes
      extra_opts: [--strip-components=1]      

  - name: start tomcat services
    command: nohup /opt/tomcat-9/bin/startup.sh
    
